// Curated sheets question slugs definitions mapping to database questions
export interface SheetMetadata {
  title: string;
  description: string;
  slugs: string[];
}

export const CURATED_SHEETS: Record<string, SheetMetadata> = {
  "blind-75": {
    title: "Blind 75 DSA Sheet",
    description: "The classic collection of 75 essential coding questions to build a strong foundation in problem solving.",
    slugs: [
      // Arrays & Hashing
      "two-sum",
      "best-time-to-buy-and-sell-stock",
      "contains-duplicate",
      "product-of-array-except-self",
      "maximum-subarray",
      "maximum-product-subarray",
      "find-minimum-in-rotated-sorted-array",
      "search-in-rotated-sorted-array",
      "3sum",
      "container-with-most-water",
      // Two Pointers & Sliding Window
      "valid-palindrome",
      "longest-substring-without-repeating-characters",
      "longest-repeating-character-replacement",
      "minimum-window-substring",
      // Stacks
      "valid-parentheses",
      // Binary Search
      "binary-search",
      // Linked Lists
      "reverse-linked-list",
      "linked-list-cycle",
      "merge-two-sorted-lists",
      "merge-k-sorted-lists",
      "remove-nth-node-from-end-of-list",
      "reorder-list",
      // Trees
      "invert-binary-tree",
      "maximum-depth-of-binary-tree",
      "same-tree",
      "subtree-of-another-tree",
      "lowest-common-ancestor-of-a-binary-search-tree",
      "binary-tree-level-order-traversal",
      "validate-binary-search-tree",
      "kth-smallest-element-in-a-bst",
      "binary-tree-maximum-path-sum",
      "serialize-and-deserialize-binary-tree",
      "construct-binary-tree-from-preorder-and-inorder-traversal",
      // Tries
      "implement-trie-prefix-tree",
      "design-add-and-search-words-data-structure",
      "word-search-ii",
      // Heap / Priority Queue
      "top-k-frequent-elements",
      "find-median-from-data-stream",
      // Backtracking
      "combination-sum",
      "word-search",
      // Graphs
      "clone-graph",
      "course-schedule",
      "pacific-atlantic-water-flow",
      "number-of-islands",
      "longest-consecutive-sequence",
      "alien-dictionary",
      "graph-valid-tree",
      "number-of-connected-components-in-an-undirected-graph",
      // Advanced Graphs
      "reconstruct-itinerary",
      "min-cost-to-connect-all-points",
      "network-delay-time",
      "swim-in-rising-water",
      "alien-dictionary",
      // Dynamic Programming
      "climbing-stairs",
      "coin-change",
      "longest-increasing-subsequence",
      "longest-common-subsequence",
      "word-break",
      "house-robber",
      "house-robber-ii",
      "decode-ways",
      "unique-paths",
      "jump-game",
      // Bit Manipulation
      "sum-of-two-integers",
      "number-of-1-bits",
      "counting-bits",
      "reverse-bits",
      "missing-number"
    ]
  },
  "neetcode-150": {
    title: "NeetCode 150 DSA Sheet",
    description: "A comprehensive list of 150 highly curated questions covering every critical interview pattern.",
    slugs: [
      // Arrays & Hashing
      "contains-duplicate",
      "valid-anagram",
      "two-sum",
      "group-anagrams",
      "top-k-frequent-elements",
      "product-of-array-except-self",
      "valid-sudoku",
      "encode-and-decode-strings",
      "longest-consecutive-sequence",
      // Two Pointers
      "valid-palindrome",
      "two-sum-ii-input-array-is-sorted",
      "3sum",
      "container-with-most-water",
      "trapping-rain-water",
      // Sliding Window
      "best-time-to-buy-and-sell-stock",
      "longest-substring-without-repeating-characters",
      "longest-repeating-character-replacement",
      "permutation-in-string",
      "minimum-window-substring",
      "sliding-window-maximum",
      // Stack
      "valid-parentheses",
      "min-stack",
      "evaluate-reverse-polish-notation",
      "generate-parentheses",
      "daily-temperatures",
      "car-fleet",
      "largest-rectangle-in-histogram",
      // Binary Search
      "binary-search",
      "search-a-2d-matrix",
      "koko-eating-bananas",
      "find-minimum-in-rotated-sorted-array",
      "search-in-rotated-sorted-array",
      "time-based-key-value-store",
      "median-of-two-sorted-arrays",
      // Linked List
      "reverse-linked-list",
      "merge-two-sorted-lists",
      "reorder-list",
      "remove-nth-node-from-end-of-list",
      "copy-list-with-random-pointer",
      "add-two-numbers",
      "linked-list-cycle",
      "find-the-duplicate-number",
      "lru-cache",
      "merge-k-sorted-lists",
      "reverse-nodes-in-k-group",
      // Trees
      "invert-binary-tree",
      "maximum-depth-of-binary-tree",
      "diameter-of-binary-tree",
      "balanced-binary-tree",
      "same-tree",
      "subtree-of-another-tree",
      "lowest-common-ancestor-of-a-binary-search-tree",
      "binary-tree-level-order-traversal",
      "binary-tree-right-side-view",
      "count-good-nodes-in-binary-tree",
      "validate-binary-search-tree",
      "kth-smallest-element-in-a-bst",
      "construct-binary-tree-from-preorder-and-inorder-traversal",
      "binary-tree-maximum-path-sum",
      "serialize-and-deserialize-binary-tree",
      // Heap / Priority Queue
      "kth-largest-element-in-a-stream",
      "last-stone-weight",
      "k-closest-points-to-origin",
      "kth-largest-element-in-an-array",
      "task-scheduler",
      "design-twitter",
      "find-median-from-data-stream",
      // Backtracking
      "subsets",
      "combination-sum",
      "permutations",
      "subsets-ii",
      "combination-sum-ii",
      "word-search",
      "palindrome-partitioning",
      "letter-combinations-of-a-phone-number",
      "n-queens",
      // Tries
      "implement-trie-prefix-tree",
      "design-add-and-search-words-data-structure",
      "word-search-ii",
      // Graphs
      "number-of-islands",
      "clone-graph",
      "max-area-of-island",
      "pacific-atlantic-water-flow",
      "surrounded-regions",
      "course-schedule",
      "course-schedule-ii",
      "redundant-connection",
      "number-of-connected-components-in-an-undirected-graph",
      "graph-valid-tree",
      "word-ladder",
      // Advanced Graphs
      "reconstruct-itinerary",
      "min-cost-to-connect-all-points",
      "network-delay-time",
      "swim-in-rising-water",
      "alien-dictionary",
      "cheapest-flights-within-k-stops",
      // 1-D Dynamic Programming
      "climbing-stairs",
      "min-cost-climbing-stairs",
      "house-robber",
      "house-robber-ii",
      "longest-palindromic-substring",
      "palindromic-substrings",
      "decode-ways",
      "coin-change",
      "maximum-product-subarray",
      "word-break",
      "longest-increasing-subsequence",
      "partition-equal-subset-sum",
      // 2-D Dynamic Programming
      "unique-paths",
      "longest-common-subsequence",
      "best-time-to-buy-and-sell-stock-with-cooldown",
      "coin-change-ii",
      "target-sum",
      "interleaving-string",
      "longest-increasing-path-in-a-matrix",
      "distinct-subsequences",
      "edit-distance",
      "burst-balloons",
      "regular-expression-matching",
      // Greedy
      "maximum-subarray",
      "jump-game",
      "jump-game-ii",
      "gas-station",
      "hand-of-straights",
      "merge-triplets-to-form-target-triplet",
      "partition-labels",
      "valid-parenthesis-string",
      // Intervals
      "insert-interval",
      "merge-intervals",
      "non-overlapping-intervals",
      "meeting-rooms",
      "meeting-rooms-ii",
      "minimum-interval-to-include-each-query",
      // Math & Geometry
      "rotate-image",
      "spiral-matrix",
      "set-matrix-zeroes",
      "happy-number",
      "plus-one",
      "powx-n",
      "multiply-strings",
      "detect-squares",
      // Bit Manipulation
      "single-number",
      "number-of-1-bits",
      "counting-bits",
      "reverse-bits",
      "missing-number",
      "sum-of-two-integers",
      "reverse-integer"
    ]
  }
};
